version: '3.8'

services:
  web:
    build: .
    ports:
      - "${SERVER_PORT}:8000"
    env_file:
      - .env
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
